site_name: Exit from Pluripotency
repo_name: Exit-from-Pluripotency
repo_url: https://github.com/ChristelKrueger/Exit-from-Pluripotency
site_url: https://christelkrueger.github.io/Exit-from-Pluripotency

nav:
  - Home: index.md
  - QC and Quantitation: QC_and_quantitation.md
  - UMAP representation and Clustering: UMAP_representation_clustering.md
  - paper figures based on Louvain clusters: paper_figures_Louvain_clustering.md
  - Network: network.md
  - Software: software.md
  


theme: 
  name: material
  palette:
    primary: deep purple
  logo: images/clusters_for_icon.png
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables